name: greasemonkey_ai
description: GreaseMonkey AI mobile app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  flutter_sound: ^9.2.13
  just_audio: ^0.9.36
  porcupine_flutter: ^2.2.0
  supabase_flutter: ^1.10.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
