name: greasemonkey_ai
description: GreaseMonkey AI mobile app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  record: ^6.0.0
  just_audio: ^0.9.36
  porcupine_flutter: ^3.0.4
  flutter_voice_processor: ^1.0.0
  supabase_flutter: ^1.10.5
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  flutter_dotenv: ^5.1.0
  sentry_flutter: ^8.14.2
  permission_handler: ^11.3.1

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  sign_in_with_apple: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/greasemonkey.ppn
    - assets/porcupine_params.pv

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: bruno-amorim
