workflows:
  flutter-workflow:
    name: GreaseMonkey AI Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BACKEND_URL: "https://greasemonkey.gupler.io"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/frontend/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd frontend
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd frontend
          flutter analyze
      - name: Flutter unit tests
        script: |
          cd frontend
          flutter test
      - name: Build APK with Flutter
        script: |
          cd frontend
          flutter build apk --release
    artifacts:
      - frontend/build/**/outputs/**/*.apk
      - frontend/build/**/outputs/**/mapping.txt
      - frontend/flutter_drive.log
    publishing:
      email:
        recipients:
          - bruno@gupler.io
        notify:
          success: true
          failure: true
