workflows:
  flutter-workflow:
    name: GreaseMonkey AI Flutter Build
    max_build_duration: 60

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*'
          include: true

    when:
      changeset:
        includes:
          - 'frontend/**'
          - 'codemagic.yaml'

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BACKEND_URL: "https://greasemonkey.gupler.io"

    scripts:
      - name: Set up local.properties
        script: |
          cd frontend
          mkdir -p android
          echo "flutter.sdk=$HOME/programs/flutter" > "android/local.properties"

      - name: Get Flutter packages
        script: |
          cd frontend
          flutter packages pub get

      - name: Flutter analyze
        script: |
          cd frontend
          flutter analyze

      - name: Flutter unit tests
        script: |
          cd frontend
          flutter test --coverage

      - name: Build APK with Flutter
        script: |
          cd frontend
          flutter build apk --release

      - name: Build iOS (if building for iOS)
        script: |
          cd frontend
          flutter build ios --release --no-codesign

    artifacts:
      - frontend/build/**/outputs/**/*.apk
      - frontend/build/**/outputs/**/mapping.txt
      - frontend/build/ios/iphoneos/Runner.app
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - bruno@gupler.io
        notify:
          success: true
          failure: true

      # Uncomment these when ready for store publishing
      # google_play:
      #   credentials: Encrypted(...)
      #   track: internal
      #   submit_as_draft: true

      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
      #   beta_groups:
      #     - name: "Internal Testers"
