services:
  # PWA Service - Next.js TypeScript application (standalone)
  pwa:
    build:
      context: ./pwa
      target: development
    container_name: greasemonkey-pwa
    env_file:
      - ./pwa/.env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Enable hot reload in Docker
    ports:
      - "3000:3000"
    volumes:
      - ./pwa:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  # PWA Production service (for testing production builds)
  pwa-prod:
    build:
      context: ./pwa
      target: production
    container_name: greasemonkey-pwa-prod
    env_file:
      - ./pwa/.env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"
    restart: unless-stopped
    profiles:
      - prod

networks:
  default:
    name: greasemonkey-net
