services:
  backend:
    build:
      context: ./backend
    container_name: greasemonkey-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: greasemonkey-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend

networks:
  default:
    name: greasemonkey-net
