services:
  backend:
    build:
      context: ./backend
    container_name: greasemonkey-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend-test:
    extends:
      service: backend
    container_name: greasemonkey-backend-test
    volumes:
      - ./backend:/app
    user: root
    command: sh -c "pip install pytest pytest-cov && python -m pytest tests/ -v --cov=. --cov-report=term"
    ports: []
    restart: "no"
    profiles:
      - test

  frontend:
    build:
      context: ./frontend
    container_name: greasemonkey-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend

  frontend-test:
    image: cirrusci/flutter:stable
    container_name: greasemonkey-frontend-test
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "flutter pub get && flutter test --coverage"
    profiles:
      - test

networks:
  default:
    name: greasemonkey-net
